### ISSUE TITLE
Random test failures

### ISSUE THREAD

**Issue by eserte** [pablrod/p5-Bat-Interpreter#8]
See http://matrix.cpantesters.org/?dist=Bat-Interpreter+0.007

Probably related to https://github.com/pablrod/App-BatParser/issues/2

**Comment by pablrod** [comment]
Yes, I suppose you're right!

I'm going to fix it right now!

Thank you!

**Comment by pablrod** [comment]
Last released version [0.008](https://github.com/pablrod/p5-Bat-Interpreter/releases/tag/v0.008) has the correct prerequisites. 

This seems to be fixed but I'll wait until [cpantesters](http://matrix.cpantesters.org/?dist=Bat-Interpreter+0.008) begin to publish the results.

**Comment by pablrod** [comment]
Comparing cpantesters results between [0.008](http://matrix.cpantesters.org/?dist=Bat-Interpreter+0.008) and [0.007](http://matrix.cpantesters.org/?dist=Bat-Interpreter+0.007) I'm pretty sure that the problem was the missing prerequisite. 

So, I'm going to close the issue but please don't hesitate to reopen or create a new issue in case of more failures!

Thank you!
